### ISSUE TITLE
Update conversion path in arbitrage controller and liquidation log

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/Sovryn-Watcher#19]
In the beginning we had only 1 converter contract and a correct conversion path had 3 entries:

For example usdt->rbtc:
1. usdt token contract
2. converter contract
3. wrbtc token contract

Now we have more hops and if we want to exchange usdt->bpro we have 5 entries:

1. usdt contract
2. converter contract
3. wrbtc contract
4. other converter contract
5. bpro contract

Update the arbitrage controller and liquidation log accordingly.

**Comment by Bitcoinera** [comment]
I think some amount of bugs come from this "bpro" thing. 

For example, looking at the code from the `getRBtcPrices` function, I see the "bpro" part is commented out, so in `arbitrage.js` we are not even getting the "bpro" prices.

I guess we should uncomment this, because otherwise the arbitrage for BPRO won't work.

Or another issue... but before the logs this should be in place too
